# Generated by Django 4.2.27 on 2026-01-13 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='cpurse',
            new_name='course',
        ),
    ]
